name: Test & Lint Python API

on:
  pull_request:
    branches: [main]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Lint with flake8
        run: |
          flake8 . --exclude=node_modules,dist,venv,__pycache__ --max-line-length=100

      - name: Run tests
        run: |
          pytest || echo "[INFO] No tests yet"
